# Numpy Creation

In [1]:
a = range(10)
a

range(0, 10)

In [2]:
import numpy as np

In [37]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr2 = np.zeros((2,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## Dimensions

shape of your data

## Attributes

ndim

In [39]:
arr1.ndim

1

In [40]:
arr2.ndim

2

Shape

In [41]:
arr1.shape

(10,)

In [42]:
arr2.shape

(2, 3)

In [43]:
# size

arr1.size

10

In [44]:
arr2.size

6

In [45]:
# dtype

In [46]:
arr1.dtype

dtype('int64')

In [47]:
arr1.itemsize

8

In [48]:
ar  = np.array([1, 2, 3], dtype=np.int32)

In [49]:
ar.itemsize

4