In [ ]:
import numpy as np
series = np.array(['Dark', 'Wednesday', 'Money heist', 'Squid game', 'Stranger thing'])
rating = np.array([8.8, 8.1, 8.2, 8.0, 8.7])

In [18]:
# ascending sort

In [35]:
np.sort(rating)

array([8. , 8.1, 8.2, 8.7, 8.8])

In [19]:
# descending sort

In [36]:
np.sort(rating)[::-1]

array([8.8, 8.7, 8.2, 8.1, 8. ])

In [20]:
# argsort

In [38]:
idx  =np.argsort(rating)[::-1]

In [39]:
series[idx[0]]

np.str_('Dark')

In [21]:
# partition

In [40]:
np.partition(rating, -2)

array([8. , 8.1, 8.2, 8.7, 8.8])

In [41]:
np.partition(rating, -2)[-2:]

array([8.7, 8.8])

In [22]:
# 2d dimensional array

In [23]:
user = np.array(['Alex', 'Sara', 'Emma'])
series = np.array(['Dark', 'Wednesday', 'Money heist'])
friends_rating = np.array([[9,7,8],
                           [8,9,6],
                           [7, 8, 6]])

In [42]:
np.sort(friends_rating, axis=1)

array([[7, 8, 9],
       [6, 8, 9],
       [6, 7, 8]])

In [43]:
np.sort(friends_rating, axis=0)

array([[7, 7, 6],
       [8, 8, 6],
       [9, 9, 8]])